[project]
name = "aer-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bs4>=0.0.2",
    "fake-useragent>=2.2.0",
    "mcp[cli]>=1.6.0",
    "requests>=2.32.3",
    "selenium>=4.31.0",
]
